[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
invilink = "98cFPPr2S2UjSthTxmjNsPei9Ty6vFcsLkyWLsTz4CTY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
