[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
invilink = "35kDpALc3cEUUWeWGZkHnThjs2R3zCNq4b4FXZ1eqZFM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/alternator/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
