[toolchain]
anchor_version = "0.30.1"
cluster = "localnet"
sbf_version = "v2"


[features]
resolution = true
skip-lint = false

[programs.localnet]
invilink = "8NnF5fcT4oxNFHSsfJ8hNaAqt9tSEdnmeErn44YcfyDq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/alternator/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
