[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
invilink = "DqZf5dE14GCM541qRBNipykFFHDMe2DKxshWk2Q4McMU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
